# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: true
    
- task: NuGetToolInstaller@0

- task: CopyFiles@2
  inputs:
    SourceFolder: 'dep/packages/'
    Contents: '**'
    TargetFolder: '$(Agent.BuildDirectory)/Nuget/dep/packages/'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.Config'
    versioningScheme: 'off'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
